import { useRef, useEffect, useState } from 'react';
import { Renderer, Program, Triangle, Mesh } from 'ogl';
import './LightRays.css';
const h2r = (h) => { const m = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(h); return m ? [parseInt(m[1],16)/255,parseInt(m[2],16)/255,parseInt(m[3],16)/255] : [1,1,1]; };
const pO = (o,w,h) => { const M = { 'top-left':[0,-.2*h,0,1],'top-right':[w,-.2*h,0,1],'left':[-.2*w,.5*h,1,0],'right':[(1+.2)*w,.5*h,-1,0],'bottom-left':[0,(1+.2)*h,0,-1],'bottom-center':[.5*w,(1+.2)*h,0,-1],'bottom-right':[w,(1+.2)*h,0,-1] }; const r = M[o] || [.5*w,-.2*h,0,1]; return {a:[r[0],r[1]],d:[r[2],r[3]]}; };
const vert = "attribute vec2 p;void main(){gl_Position=vec4(p,0.0,1.0);}";
const frag = "precision highp float;uniform float iT;uniform vec2 iR;uniform vec3 c;uniform float sp;uniform float ls;uniform float rl;uniform float sa;uniform vec2 rP;uniform vec2 rD;uniform vec2 mP;uniform float mI;float h(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float n(vec2 p){vec2 i=floor(p);vec2 fr=fract(p);fr=fr*fr*(3.-2.*fr);float a=h(i);float b=h(i+vec2(1.,0.));float c=h(i+vec2(0.,1.));float d=h(i+vec2(1.,1.));return mix(mix(a,b,fr.x),mix(c,d,fr.x),fr.y);}void main(){vec2 uv=gl_FragCoord.xy/iR.xy;vec2 fc=gl_FragCoord.xy;vec2 d=normalize(rD);vec2 tf=fc-rP;float pL=dot(tf,d);float pD=length(tf-pL*d);float t=iT*sp;float sa2=.15+ls*.6;float aw=exp(-pD*pD*500./(sa2*sa2*iR.y));float lf=1.-smoothstep(0.,rl*iR.y,pL);float ri=aw*lf;if(mI>.0){ri*=(1.+exp(-length(mP-uv)*4.)*mI);}vec3 col=mix(vec3(dot(vec3(ri),vec3(.299,.587,.114))),vec3(ri)*c,sa);float a2=max(col.r,max(col.g,col.b));gl_FragColor=vec4(col,a2);}";
export default function LightRays({raysOrigin='top-center',raysColor='#ffffff',raysSpeed=1,lightSpread=.5,rayLength=1,saturation=1,followMouse=false,mouseInfluence=.5,className=''}) {
  const ref = useRef(null); const ur=useRef(null); const rr=useRef(null); const mr=useRef({x:.5,y:.5}); const sr=useRef({x:.5,y:.5}); const ar=useRef(null); const mr2=useRef(null); const cr=useRef(null); const [v,sv]=useState(false);
  useEffect(()=>{if(!ref.current)return;const o=new IntersectionObserver(e=>sv(e[0].isIntersecting),{threshold:.1});o.observe(ref.current);return()=>o.disconnect();},[]);
  useEffect(()=>{if(!v||!ref.current)return;if(cr.current){cr.current();cr.current=null;}(async()=>{if(!ref.current)return;await new Promise(r=>setTimeout(r,10));if(!ref.current)return;const ren=new Renderer({dpr:Math.min(window.devicePixelRatio,2),alpha:true});rr.current=ren;const gl=ren.gl;gl.canvas.style.width='100%';gl.canvas.style.height='100%';while(ref.current.firstChild)ref.current.removeChild(ref.current.firstChild);ref.current.appendChild(gl.canvas);const rgb=h2r(raysColor);const p=pO(raysOrigin,1,1);const u={iT:{value:0},iR:{value:[1,1]},c:{value:rgb},sp:{value:raysSpeed},ls:{value:lightSpread},rl:{value:rayLength},sa:{value:saturation},rP:{value:p.a},rD:{value:p.d},mP:{value:[.5,.5]},mI:{value:mouseInfluence}};ur.current=u;const mesh=new Mesh(gl,{geometry:new Triangle(gl),program:new Program(gl,{vertex:vert,fragment:frag,uniforms:u})});mr2.current=mesh;const rs=()=>{if(!ref.current||!ren)return;const w=ref.current.clientWidth,h=ref.current.clientHeight;ren.setSize(w,h);const dpr=ren.dpr;u.iR.value=[w*dpr,h*dpr];const p2=pO(raysOrigin,w*dpr,h*dpr);u.rP.value=p2.a;u.rD.value=p2.d;};const loop=t=>{if(!rr.current||!ur.current||!mr2.current)return;u.iT.value=t*.001;if(followMouse&&mouseInfluence>0){sr.current.x=sr.current.x*.92+mr.current.x*.08;sr.current.y=sr.current.y*.92+mr.current.y*.08;u.mP.value=[sr.current.x,sr.current.y];}ren.render({scene:mesh});ar.current=requestAnimationFrame(loop);};window.addEventListener('resize',rs);rs();ar.current=requestAnimationFrame(loop);cr.current=()=>{if(ar.current)cancelAnimationFrame(ar.current);window.removeEventListener('resize',rs);if(ren){try{const lc=ren.gl.getExtension('WEBGL_lose_context');if(lc)lc.loseContext();if(gl.canvas&&gl.canvas.parentNode)gl.canvas.parentNode.removeChild(gl.canvas);}catch(e){}}rr.current=null;ur.current=null;mr2.current=null;};})();return()=>{if(cr.current){cr.current();cr.current=null;}};},[v,raysOrigin,raysColor,raysSpeed,lightSpread,rayLength,saturation,followMouse,mouseInfluence]);
  useEffect(()=>{const h=e=>{if(!ref.current||!rr.current)return;const r=ref.current.getBoundingClientRect();mr.current={x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height};};if(followMouse){window.addEventListener('mousemove',h);return()=>window.removeEventListener('mousemove',h);}},[followMouse]);
  return <div ref={ref} className={'light-rays-container '+className} />;
}